apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: vpw
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plainhost
        port: 9092
        type: internal
        tls: false
      - name: plain
        port: 9192
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}