apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgres
    chart: postgres
    heritage: Helm
    component:  postgres
data:
  postgresql-password: "dnB3"   #vpw base64
  postgresql-postgres-password: ""