##
 # This workflow executes all relevant tests for pipeline, analyzer & vpw-shared-elasticsearch-config.
##

name: Test pipeline, analyzer & vpw-shared-elasticsearch-config

# Triggered by push or pull request on branch main or develop
on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Execution of tests for pipeline, analyzer & vpw-shared-elasticsearch-config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Execute tests for pipeline, analyzer & vpw-shared-elasticsearch-config
        # The *verify* command executes each default lifecycle phase in order: validate -> compile -> test -> package, before executing verify.
        # In most cases the effect is the same as package. However, in case there are integration-tests, these will be executed as well.
        run: |
          mvn --batch-mode --update-snapshots verify
