##
# This workflow pushes helm charts to viadee/charts repository
##

name: Push vpw-analyzer-chart to viadee/charts repository

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/helm/vpw-analyzer-chart/**'

jobs:
  update-chart-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout viadee/vPW repository
        uses: actions/checkout@v2
        with:
          path: vpw

      - name: Checkout viadee/charts repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_VIADEE_GITHUB_VPW }}
          repository: viadee/charts
          path: charts

      #
      ## ANALYZER
      #

      - name: Apply changes to viadee/charts repository - analyzer
        run: |
          rm -rfv ./charts/charts/vpw-analyzer-chart
          cp -rv ./vpw/deployment/helm/vpw-analyzer-chart ./charts/charts/

      - name: Extract chart versions - analyzer
        run: |
          helm show chart charts/charts/vpw-analyzer-chart > chart-infos-analyzer.txt
          version_analyzer=$( cat ./chart-infos-analyzer.txt | egrep "(version)(:)(\s)([0-9]+.[0-9]+.[0-9]+)" | egrep "([0-9]+.[0-9]+.[0-9]+)" -o)
          echo $version_analyzer
          echo "CHART_VERSION_ANALYZER=$version_analyzer" >> $GITHUB_ENV

      - name: Create pull request - analyzer
        id: cpr-analyzer
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_VIADEE_GITHUB_VPW }}
          path: ./charts
          base: main
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: "Update vpw-analyzer-chart to version ${{ env.CHART_VERSION_ANALYZER }}"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: vpw-analyzer-chart-${{ env.CHART_VERSION_ANALYZER }}
          delete-branch: true
          title: vpw-analyzer-chart-${{ env.CHART_VERSION_ANALYZER }}
          body: "Update vpw-analyzer-chart to version ${{ env.CHART_VERSION_ANALYZER }}"
          draft: false
          labels: automated-created-pr

      - name: Check pull request - analyzer
        run: |
          echo "Pull Request Number - ${{ steps.cpr-analyzer.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr-analyzer.outputs.pull-request-url }}"